name: Cypress tests

on:
  push:
    branches:
      - main # Modify this to your relevant branch if needed

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: ci_run
        uses: cypress-io/github-action@v6

      # Archive screenshots and videos if tests fail
      - name: Archive Cypress screenshots and videos
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: cypress/screenshots, cypress/videos
